### ISSUE TITLE
《Power Allocation in Multi-cell Networks Using Deep Reinforcement Learning》这篇论文的链接请求！

### ISSUE THREAD

**Issue by zhuwenxing** [kangcp/qfnet#1]
你好，我根据在readme中你给出的论文题目去搜索，并没有找到完全同名的论文，您可以给出该论文的地址链接吗？

**Comment by M1ddlzh** [comment]
https://arxiv.org/abs/1812.02979

**Comment by M1ddlzh** [comment]
> 你好，我根据在中你给出的论文题目去搜索，并没有找到完全同名的论文，您可以给出该论文的地址链接吗？

https://arxiv.org/abs/1812.02979

**Comment by zhuwenxing** [comment]
> > 你好，我根据在中你给出的论文题目去搜索，并没有找到完全同名的论文，您可以给出该论文的地址链接吗？
> 
> https://arxiv.org/abs/1812.02979

Hi,
当时搜到了这篇论文，但是看题目是Power Allocation in Multi-user Cellular Networks With Deep Q Learning Approach，并没有完全重名，有一些差别，就想在issue中确认一下。
BTW，我发邮件问过论文“Power Allocation in Multi-user Cellular Networks With Deep Q Learning Approach”的作者，这不是他们写的。
